# development-icovn --> enviroment profile
# jmsTransfer --> message transfer profile
# linebotProcessor --> processor profile
# simpleAlert --> alert profile
spring.profiles.active: development-icovn,jmsTransfer,linebotProcessor,simpleAlert

# LOGGING
#logging.config: logback.xml